#**FAKE NEWS CLASSIFIER USING Bidirectional LSTM

In [1]:
import pandas as pd


In [2]:
df =pd.read_csv('/content/FakeNewsNet.csv')

In [3]:
df.head(20)

title  \
0   Kandi Burruss Explodes Over Rape Accusation on...   
1   People's Choice Awards 2018: The best red carp...   
2   Sophia Bush Sends Sweet Birthday Message to 'O...   
3   Colombian singer Maluma sparks rumours of inap...   
4   Gossip Girl 10 Years Later: How Upper East Sid...   
5   Gwen Stefani Got Dumped by Blake Shelton Over ...   
6   Broward County Sheriff Fired For Lying About P...   
7   Amber Rose Shuts Down French Montana Dating Ru...   
8   Mindy Kaling makes first post-baby appearance ...   
9   Katharine McPhee Butchers Tony Nominations: “I...   
10  ‘WAGS Miami’ Stars Ashley Nicole Roberts and P...   
11  Mel Gibson: Hollywood Pedophiles Have Nowhere ...   
12  Medium Tyler Henry Addresses The ‘Chilling’ Me...   
13      DWTS Season 27 Results: Week 5 - Disney Night   
14        2011 via CQ subscribers only Tax Foundation   
15  5 Reasons Why Tarek El Moussa Will Overcome Hi...   
16  David Cassidy cuts estranged daughter Katie co...   
17  Actress Brigitte Nielsen, 54, has given birth ...   
18  The Kardashians donate whopping sum to Las Veg...   
19  Is Brad Pitt Open To Getting Back Together Wit...   

                                             news_url          source_domain  \
0   http://toofab.com/2017/05/08/real-housewives-a...             toofab.com   
1   https://www.today.com/style/see-people-s-choic...          www.today.com   
2   https://www.etonline.com/news/220806_sophia_bu...       www.etonline.com   
3   https://www.dailymail.co.uk/news/article-33655...    www.dailymail.co.uk   
4   https://www.zerchoo.com/entertainment/gossip-g...        www.zerchoo.com   
5   www.intouchweekly.com/posts/gwen-stefani-dumpe...  www.intouchweekly.com   
6   https://yournewswire.com/broward-county-sherif...       yournewswire.com   
7   www.etonline.com/news/214798_amber_rose_shuts_...       www.etonline.com   
8   https://www.aol.com/article/entertainment/2018...            www.aol.com   
9   https://www.98online.com/2018/05/02/katharine-...       www.98online.com   
10  https://www.usmagazine.com/celebrity-news/news...     www.usmagazine.com   
11  yournewswire.com/mel-gibson-hollywood-pedophiles/       yournewswire.com   
12  https://perezhilton.com/tyler-henry-says-krist...        perezhilton.com   
13  https://abc.go.com/shows/dancing-with-the-star...             abc.go.com   
14                                                NaN                    NaN   
15  www.eonline.com/news/932478/5-reasons-why-tare...        www.eonline.com   
16  https://www.thesun.co.uk/news/5086439/david-ca...       www.thesun.co.uk   
17  https://www.usatoday.com/story/life/people/201...       www.usatoday.com   
18  https://web.archive.org/web/20171228144534/htt...        web.archive.org   
19  hollywoodlife.com/2017/08/27/would-brad-pitt-g...      hollywoodlife.com   

    tweet_num  real  
0        42.0   1.0  
1         0.0   1.0  
2        63.0   1.0  
3        20.0   1.0  
4        38.0   1.0  
5        45.0   0.0  
6       124.0   0.0  
7         4.0   0.0  
8        59.0   1.0  
9        10.0   1.0  
10       18.0   1.0  
11       95.0   0.0  
12        4.0   1.0  
13        0.0   1.0  
14        0.0   1.0  
15       63.0   0.0  
16       54.0   1.0  
17       64.0   1.0  
18        1.0   0.0  
19       19.0   0.0

In [4]:
df.tail()

title  \
16944  Investor, former 'Property Wars' star sentence...   
16945      Mama June: From Not to Hot – Episodes – WE tv   
16946  Chrissy Teigen and John Legend Can’t Choose a ...   
16947  Modern Family's Sarah Hyland shuts down anorex...   
16948                            Naya Rivera Is All Smil   

                                                news_url  \
16944  https://www.azcentral.com/story/news/local/pho...   
16945  http://www.wetv.com/shows/mama-june-from-not-t...   
16946  https://www.realsimple.com/work-life/entertain...   
16947  https://www.nowtolove.com.au/health/body/sarah...   
16948                                                NaN   

              source_domain  tweet_num  real  
16944     www.azcentral.com       43.0   1.0  
16945          www.wetv.com       47.0   1.0  
16946    www.realsimple.com       66.0   1.0  
16947  www.nowtolove.com.au      132.0   1.0  
16948                   NaN        NaN   NaN

In [5]:
df.shape

(16949, 5)

In [6]:
df.isnull().sum()

title              0
news_url         231
source_domain    231
tweet_num          1
real               1
dtype: int64

In [7]:
#dropping the null values
df = df.dropna()

In [8]:
df.head()

title  \
0  Kandi Burruss Explodes Over Rape Accusation on...   
1  People's Choice Awards 2018: The best red carp...   
2  Sophia Bush Sends Sweet Birthday Message to 'O...   
3  Colombian singer Maluma sparks rumours of inap...   
4  Gossip Girl 10 Years Later: How Upper East Sid...   

                                            news_url        source_domain  \
0  http://toofab.com/2017/05/08/real-housewives-a...           toofab.com   
1  https://www.today.com/style/see-people-s-choic...        www.today.com   
2  https://www.etonline.com/news/220806_sophia_bu...     www.etonline.com   
3  https://www.dailymail.co.uk/news/article-33655...  www.dailymail.co.uk   
4  https://www.zerchoo.com/entertainment/gossip-g...      www.zerchoo.com   

   tweet_num  real  
0       42.0   1.0  
1        0.0   1.0  
2       63.0   1.0  
3       20.0   1.0  
4       38.0   1.0

In [9]:
# getting the independence feature
x= df.drop('real', axis=1)

In [10]:
y= df['real']

In [11]:
df.shape

(16718, 5)

In [12]:
y.shape

(16718,)

In [13]:
import tensorflow as tf


In [14]:
tf.__version__

'2.19.0'

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [16]:
voc_size=1000

one hot encoding


In [17]:
message =x.copy()

In [18]:
message['title'][1]

"People's Choice Awards 2018: The best red carpet looks"

In [19]:
message

title  \
0      Kandi Burruss Explodes Over Rape Accusation on...   
1      People's Choice Awards 2018: The best red carp...   
2      Sophia Bush Sends Sweet Birthday Message to 'O...   
3      Colombian singer Maluma sparks rumours of inap...   
4      Gossip Girl 10 Years Later: How Upper East Sid...   
...                                                  ...   
16943  Angelina Jolie & Brad Pitt Have ‘Secret Rendez...   
16944  Investor, former 'Property Wars' star sentence...   
16945      Mama June: From Not to Hot – Episodes – WE tv   
16946  Chrissy Teigen and John Legend Can’t Choose a ...   
16947  Modern Family's Sarah Hyland shuts down anorex...   

                                                news_url  \
0      http://toofab.com/2017/05/08/real-housewives-a...   
1      https://www.today.com/style/see-people-s-choic...   
2      https://www.etonline.com/news/220806_sophia_bu...   
3      https://www.dailymail.co.uk/news/article-33655...   
4      https://www.zerchoo.com/entertainment/gossip-g...   
...                                                  ...   
16943  hollywoodlife.com/2017/07/17/angelina-jolie-br...   
16944  https://www.azcentral.com/story/news/local/pho...   
16945  http://www.wetv.com/shows/mama-june-from-not-t...   
16946  https://www.realsimple.com/work-life/entertain...   
16947  https://www.nowtolove.com.au/health/body/sarah...   

              source_domain  tweet_num  
0                toofab.com       42.0  
1             www.today.com        0.0  
2          www.etonline.com       63.0  
3       www.dailymail.co.uk       20.0  
4           www.zerchoo.com       38.0  
...                     ...        ...  
16943     hollywoodlife.com       15.0  
16944     www.azcentral.com       43.0  
16945          www.wetv.com       47.0  
16946    www.realsimple.com       66.0  
16947  www.nowtolove.com.au      132.0  

[16718 rows x 4 columns]

In [20]:
import nltk
import re
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [22]:
# data preprocessing

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus =[]
message = message.reset_index(drop=True) # Reset index after dropping nulls
for i in range(0,len(message)):
  review =re.sub('[^a-zA-Z]', ' ', message['title'][i])
  review = review.lower()
  review = review.split()


  review =[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [23]:
corpus

['kandi burruss explod rape accus real housew atlanta reunion video',
 'peopl choic award best red carpet look',
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva',
 'colombian singer maluma spark rumour inappropri relationship aunt',
 'gossip girl year later upper east sider shock world chang pop cultur forev',
 'gwen stefani got dump blake shelton jealousi drama exclus',
 'broward counti sheriff fire lie parkland',
 'amber rose shut french montana date rumor call rapper bruvaaa',
 'mindi kale make first post babi appear disneyland wrinkl time co star',
 'katharin mcphee butcher toni nomin drink',
 'wag miami star ashley nicol robert philip wheeler marri',
 'mel gibson hollywood pedophil nowher left hide',
 'medium tyler henri address chill messag kristin cavallari deceas brother express read',
 'dwt season result week disney night',
 'reason tarek el moussa overcom latest back injuri',
 'david cassidi cut estrang daughter kati complet leav son b

In [24]:
corpus[1]

'peopl choic award best red carpet look'

In [25]:
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[471, 760, 475, 269, 651, 747, 738, 507, 907, 483],
 [167, 376, 279, 776, 270, 741, 693],
 [576, 931, 143, 450, 630, 164, 242, 653, 86, 545, 436, 948, 885, 666, 917],
 [922, 310, 66, 317, 767, 831, 263, 308],
 [371, 69, 808, 789, 714, 616, 222, 861, 232, 177, 818, 831, 212],
 [753, 154, 928, 112, 801, 766, 840, 86, 606],
 [280, 805, 413, 410, 870, 736],
 [30, 113, 221, 547, 102, 43, 341, 256, 214, 363],
 [567, 659, 765, 168, 257, 58, 311, 940, 812, 387, 545, 436],
 [551, 815, 133, 2, 894, 434],
 [389, 576, 436, 432, 385, 293, 216, 866, 320],
 [100, 616, 297, 413, 284, 127, 885],
 [238, 382, 227, 510, 517, 164, 615, 884, 309, 105, 204, 503],
 [239, 472, 170, 532, 599, 421],
 [217, 582, 651, 854, 809, 11, 138, 714],
 [216, 923, 534, 914, 57, 484, 489, 903, 89, 159],
 [353, 651, 780, 136, 98, 820, 890],
 [798, 323, 495, 816, 256, 633, 47, 986, 362],
 [725, 963, 580, 488, 138, 266, 8, 341],
 [618, 321, 812, 253, 896, 125],
 [363, 263, 580, 653, 279, 673, 589, 693, 589, 487, 781, 194, 686]

In [26]:
onehot_repr[1]

[167, 376, 279, 776, 270, 741, 693]

  embedding represntation

In [27]:
sent_length=20
embedded_docs =pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0   0 ... 507 907 483]
 [  0   0   0 ... 270 741 693]
 [  0   0   0 ... 885 666 917]
 ...
 [  0   0   0 ... 408 227 617]
 [  0   0   0 ... 197  58 831]
 [  0   0   0 ... 202 945 177]]


In [28]:
embedded_docs[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
       167, 376, 279, 776, 270, 741, 693], dtype=int32)

# CREATING THE MODEL

In [29]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.build(input_shape=(None, sent_length))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 20, 40)         │        40,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 200)            │       112,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 153,001 (597.66 KB)

 Trainable params: 153,001 (597.66 KB)

 Non-trainable params: 0 (0.00 B)

None


In [30]:
len(embedded_docs), y.shape

(16718, (16718,))

In [31]:
import numpy as np
x_final =np.array(embedded_docs)
y_final =np.array(y)

In [32]:
x_final.shape, y_final.shape

((16718, 20), (16718,))

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_final,y_final, test_size=0.33, random_state=42)

In [34]:
##finally taining the model
model.fit(x_train,y_train, validation_data=(x_test,y_test), epochs=10, batch_size=64)

Epoch 1/10
176/176 ━━━━━━━━━━━━━━━━━━━━ 7s 13ms/step - accuracy: 0.7564 - loss: 0.5455 - val_accuracy: 0.8082 - val_loss: 0.4567
Epoch 2/10
176/176 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8220 - loss: 0.4313 - val_accuracy: 0.8082 - val_loss: 0.4404
Epoch 3/10
176/176 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8291 - loss: 0.3955 - val_accuracy: 0.8122 - val_loss: 0.4396
Epoch 4/10
176/176 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8339 - loss: 0.3818 - val_accuracy: 0.8099 - val_loss: 0.4421
Epoch 5/10
176/176 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.8359 - loss: 0.3783 - val_accuracy: 0.8042 - val_loss: 0.4478
Epoch 6/10
176/176 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8504 - loss: 0.3436 - val_accuracy: 0.8104 - val_loss: 0.4515
Epoch 7/10
176/176 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8536 - loss: 0.3376 - val_accuracy: 0.7932 - val_loss: 0.4751
Epoch 8/10
176/176 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8664 - loss: 0.3089 - val_accuracy

# PERFORMANCE METICS AND ACCURACY

In [35]:
y_pred = model.predict(x_test)


173/173 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step


In [36]:
y_pred =np.where(y_pred>0.5,1,0) #AUC ROC CURVE


In [37]:
from sklearn.metrics import confusion_matrix

In [38]:
confusion_matrix(y_test,y_pred)

array([[ 548,  791],
       [ 302, 3876]])

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8018850824723581

In [40]:
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.64      0.41      0.50      1339
         1.0       0.83      0.93      0.88      4178

    accuracy                           0.80      5517
   macro avg       0.74      0.67      0.69      5517
weighted avg       0.79      0.80      0.79      5517

